### PR TITLE
Addresses spoofing of X-Forwarded-For by adding safe default

### PR DESCRIPTION
**Pull request by brendensoares**
Follow up to #6 

@anonx how's this look? Also, please peak at revel/revel.github.io#53.

### CODE REVIEW

**Comment by anonx** [comment]
:+1:
As for https://revel/revel.github.io#53 Can we also explicitly describe the consequences of enabling `jobs.acceptproxyaddress` option? Like it should be only used if you have nginx or some other proxy server in front of your app instance. Otherwise, the combination of enabled `jobs` module and that option turned on may lead to a possibility of unauthorized access.

**Comment by brendensoares** [comment]
@anonx describing the consequences sounds good. Do you have any recommended copy? If not, I can whip something up.

**Comment by anonx** [comment]
@brendensoares 
> Do you have any recommended copy?

Not really. Apparently writing is not my strongest point.

**Comment by brendensoares** [comment]
The documentation PR has been updated.

**Pull request merged**
