### PR TITLE
Gorm module

### PR DESCRIPTION
**Pull request by wariosolis**
modules/gorm
===============

[Gorm](http://jinzhu.me/gorm) module

## Activation
```ini
module.gorm = github.com/revel/modules/gorm
```

## Drivers

* sqlite3
* postgres
* mysql

## Configuration file

```ini
# Database config
db.autoinit = true # true | false
db.driver=sqlite # mysql, postgres, sqlite3
db.host=localhost  # Use dbhost  /tmp/gorm.db is your driver is sqlite
db.user=dbuser
db.name=dbname
db.password=dbpassword
```

Example Auto init DB:
```
import (
"github.com/revel/revel"
"github.com/revel/modules/gorm/app"
)

type App struct {
	*revel.Controller
	gorm.GormController
}
```

Example Manual Init DB:
```
import (
"github.com/revel/revel"
"github.com/revel/modules/gorm/app"
)

type App struct {
	*revel.Controller
	gorm.GormController
}


func (c App) Index() revel.Result {
	params := gorm.DbInfo{}
	params.DbDriver = "sqlite3"
	params.DbHost = "/tmp/dbtest.db"
	params.DbName = "test"
	params.DbPassword = "test"
	params.DbUser = "test"
	gorm.InitDBWithParameters(params)

	return c.Render()
}
```

### CODE REVIEW

**Comment by notzippy** [comment]
Sorry for the delay, I like the design of the module. I wonder if you could enhance this a little bit.
- [ ] Add ability to turn of the InitDB that the init calls from a configuration option.
- [ ] Expand the InitDB function so that the dbDrive,dbHost, dbUser, dbName, dbPassword 

I always seem to run in the situation where I need two different database connections so if the controller could be flexible enough to have this then (but default to the auto config) that would be great.

And since we are adding easy DB mapping can you provide a function to get a [sq.StatementBuilder](https://github.com/Masterminds/squirrel) All this method needs to do is check to see if the sqlDriver is postgres, if it is return this `sq.StatementBuilder.PlaceholderFormat(sq.Dollar)` , if not return `sq.StatementBuilder.PlaceholderFormat(sq.Question)`

**Comment by wariosolis** [comment]
I will work on the suggested changes and keep you informed

**Comment by notzippy** [comment]
Have you made any progress with this ?

**Comment by wariosolis** [comment]
Sorry for the delay, but I had a lot of work.

**Comment by Steve-hyas** [comment]
No problems @wariosolis , thanks for the update !

**Comment by notzippy** [comment]
No problems @wariosolis , thanks for the update

**Comment by wariosolis** [comment]
I have pending adding the function to get the sql.Statement Builder, although I think that's part of Gorm and not the module itself.

I await your comments for errors or additions.

**Comment by pedromorgan** [comment]
So the only comment I have is the config, which seems to conflict with the "keys" used in the manual 

http://revel.github.io/manual/appconf.html#database
ie
```
db.*
vs
app.db*
```

Prefer the ```dd.*``` persnally

**Comment by wariosolis** [comment]
Ok, i'll change the config to db.*

**Comment by wariosolis** [comment]
Fixed.

**Comment by brendensoares** [comment]
The initial code sample doesn't appear to have a `gorm` package as you're importing `gorm/app`, is that right? Can you also demo a basic select query from within a Revel Controller method?

This looks pretty good so far.

**Comment by wariosolis** [comment]
I have made an example of the module and added it to the examples repository.
Https://github.com/revel/examples/pull/29

**Pull request merged**
