### PR TITLE
Adding MIT license information to the project

### PR DESCRIPTION
**Pull request by corgrath**
By adding an open source license, other developers don't need to worry about how it may or may not be used =)

### CODE REVIEW

**Comment by corgrath** [comment]
@notzippy @jeevatkm - Is this something you can help us out with? Adding an open source license to your project?

**Comment by jeevatkm** [comment]
@corgrath I'm sorry, I don't have repo write permission anymore. 
Only @notzippy @pedromorgan @brendensoares could help you.

**Comment by corgrath** [comment]
Yea, I would really appreciate this, as we have tools and audits that checks third party licensing.

I don't think its intentional that this is not open source, probably just forgotten to add the license file =)

**Comment by notzippy** [comment]
Yes, it was missed when we broke apart the project. Thanks for the PR

**Comment by corgrath** [comment]
Thanks

**Pull request merged**
