### PR TITLE
[orm/gorm] Allow configuration of singulartable:

### LINKED ISSUE #64: [orm/gorm] Allow configuration of singulartable
I'm using DB.SingularTable(true) but I have to use this code within every function of my controllers. 
I didn't find a general place to set this value and I'd expect it to be configurable using the app.conf file.

Would it be possible to add a new configuration attribute? e.g. 'db.singulartable', so there is a general and unique place where this can be configured.

### PR DESCRIPTION
**Pull request by almarto**
I want to resolve #64 with this PR.

### CODE REVIEW

**Comment by notzippy** [comment]
@almarto that looks good, can you update the README file with the new configuration parameter name ?

**Comment by almarto** [comment]
@notzippy it's already there. I added the new parameter to both files:

- modules/orm/gorm/README.md
- modules/orm/gorm/app/gorm.go

**Comment by notzippy** [comment]
Your right, I was looking for more of an explanation on what `singulartable` means but even gorms [godoc](https://godoc.org/github.com/jinzhu/gorm#DB.SingularTable) isn't clear on that. 

Perhaps if you added something in the doc like the following 


#### singulartable
By default all tables are created based on a struct are pluralized ie a  `type User struct {}` becomes table `users` in the database, by setting this to true, `User`'s default table name will be `user`. Note table names set with `TableName` won't be affected by this setting. You can also change the created table names by setting `gorm.DefaultTableNameHandler` on `AppStartup` or `func init()` see [here](http://jinzhu.me/gorm/models.html#conventions) for more details

**Comment by almarto** [comment]
Sorry for that @notzippy I didn't explain the attribute because the others aren't explained and I thought it was intended for address the user to the gorm documentation. 
I'll add a better documentation.

**Comment by notzippy** [comment]
Thanks looks much better - I am trying to improve the documents with every commit - thanks for your help. I changed the base to development which when merged should be out in the beginning of Febuary

**Pull request merged**
