### PR TITLE
Update gorm.go

### PR DESCRIPTION
**Pull request by k3a**
pointer to revel controller
fix for sqlite3 driver default options

### CODE REVIEW

**Comment by k3a** [comment]
It works but I don't know how to properly use GormController in my app controller. If I do this
```go
import gorm "github.com/revel/modules/gorm/app"
type App struct {
    gorm.GormController
}
```
Revel won't find this as a valid controller. I have to add *revel.Controller as the first field of App struct. And that looks weird.

**Comment by notzippy** [comment]
If you look at the [example](https://github.com/revel/examples/blob/master/gorm/app/controllers/app.go) that is the proper way of implementing this module. The reason you cannot extend only this modules controller is because the controller is not inside a folder called `controllers`. When Revel starts it scans all modules and the app for files in the `controllers` folder. If a struct within those files contains an embedded `*revel.Controller` then it is considered a valid controller and the exposed methods are allowed to be route end points.

**Comment by k3a** [comment]
Thanks for explanation and a link to the example. If that is the case, why GormController struct has *revel.Controller inside? It could be an empty struct, right?

**Comment by notzippy** [comment]
I am pretty sure it could be, but I haven't tried it (can you ?). This module was contributed by a user.

**Comment by k3a** [comment]
I've just tested it. So *revel.Controller is really useless and it can be:
```go
type GormController struct {
    Txn *gorm.DB
}
```
but as it is called Controller so maybe we should keep *revel.Controller in it, it's just a pointer. It should definitely be a pointer (as in my PR) though, otherwise it holds unnecessary memory space in the structure and all controllers are supposed to contain pointer type *revel.Controller.

**Comment by notzippy** [comment]
If possible, can you update your PR to remove the revel.Controller as (like you said) it is confusing. Thanks

**Comment by wariosolis** [comment]
That was my mistake.
I had problems since revel does not identify the controller if it is outside the project folder
I think that's what I was referring to in the PR https://github.com/revel/modules/pull/43.
I will correct that part tonight https://github.com/revel/modules/pull/43

**Comment by notzippy** [comment]
@wariosolis Revel can detect folders outside its the app folder as long as it is in a `controllers/` folder (I know that is weird). Check out this PR `revel/modules#52` that controller can be embedded and found by revel because it is in the `controllers` folder.

**Comment by k3a** [comment]
Wow, Revel really finds the controller if it is under `<module>/app/controllers`. Moving gorm controller there makes this code possible:

```go
package controllers

import (
    "github.com/revel/revel"
    gormc "github.com/revel/modules/gorm/app/controllers"
)

type App struct {
    gormc.GormController
}

type Toy struct {
    Name string
}

func (c App) Index() revel.Result {
    c.Txn.LogMode(true)
    c.Txn.AutoMigrate(&Toy{})
    c.Txn.Save(&Toy{Name: "Fidget spinner"})

    return c.Render()
}
```

Won't it be worth to refactor it a bit into modules/gorm/app/controller and make two versions of the controller - one using transaction, the other not + update examples? I would be happy to do it...

I think it makes more sense to include one controller class in a struct instead of both "gorm" and "revel"...

**Comment by notzippy** [comment]
@k3a That would be great if you could do that! If you could also move the package from `modules/gorm` to `modules/orm/gorm` that would be greatly appreciated too. I started thinking about this and there are a number of different ORM's that have been developed for go and it would be best if we could group them all together under a single package tree instead of in each of their own folders. 
```
modules
    |- auth
    |- orm
    |    |- Gorm
    |    |- Gorp

```
Is that possible ?

**Comment by k3a** [comment]
Ok, I've updated the PR with these changes and tested it works.

**Comment by notzippy** [comment]
@k3a There is an example implementation of Gorm in https://github.com/revel/examples/tree/master/gorm , can you make a PR to match these changes as well ? thanks

**Pull request merged**
