### PR TITLE
Testrunner enhancements

### PR DESCRIPTION
**Pull request by eric-gilbertson**
UI and functional enhancements to the test runner page
   - more condensed layout to reduce need to scroll
   - place buttons on both left and right of page for better accessibility
   - add file level run, e.g. all tests in a given suite
   - remove table striping to better show test groups
   - clear test status on test start
   - display "run all" pass/fail count link below button
   - auto scroll to first failure when run all results link is clicked

TODO:
   - display tests in dir hierarchy, e.g. controller, service, model
   - add show/hide for each test dir
   - display sorted by name
testrunner_enhancements

### CODE REVIEW

**Comment by anonx** [comment]
@eric-gilbertson :+1: Could you please target `develop` branch?

By the way, what do you think about using fontawesome icon instead of `Run` text at the right side (left side will still have just `Run` text). Something like [play](http://fontawesome.io/icon/play-circle/) or [refresh](http://fontawesome.io/icon/refresh/). We can add [`fa-spin` class](http://fontawesome.io/examples/#animated) when button is active. I think that would be cool.

**Comment by notzippy** [comment]
How about adding in folding at the test level, like this https://jsfiddle.net/n4bhbwc1/1/ that would reduce space further and make it easier to find a specific test to run.

**Comment by anonx** [comment]
@brendensoares It's `master` branch.

**Comment by brendensoares** [comment]
@anonx I'm not sure what happened. #10 was merged and then this was after it? I can't see what the changes of this PR were now. I can't revert either. What should we do to fix my mess up?

**Comment by brendensoares** [comment]
I believe [this is the missing commit](https://github.com/eric-gilbertson/revel/commit/8a9c163662089b30e5acc6265a20257e87cb2159)

**Pull request merged**
