### PR TITLE
Add Casbin authz module

### LINKED ISSUE #42: Support Casbin as the authorization (AuthZ) module
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security in authorization for Revel. So I'd like to add it to this modules repo. What do you think? Let me know if there's any question:) Thanks.

### PR DESCRIPTION
**Pull request by hsluoyz**
This PR solves: https://github.com/revel/revel/issues/1176
closes #42

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi, is anyone working on this?

**Comment by notzippy** [comment]
I was looking at it, I noticed it uses the GORM package - is there a way for you to have this integrate with the [gorm](https://github.com/revel/modules/tree/develop/orm/gorm) module ? (note on the development this module has been moved to modules/orm/gorm)

**Comment by hsluoyz** [comment]
Thanks. I have switched to use the new develop branch code in a new PR: https://github.com/revel/modules/pull/56

**Comment by notzippy** [comment]
Closing in favor of #56

**Pull request closed without merging**
